/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author Administrator
 */
public class BillandReceipt extends javax.swing.JFrame {
    private String mnumber;
    private String date;
    private String previous;
    private String current;
    private String unitconsumed;
    private String totalpayable;
    private String updname;
    private String updadd;
    private String updphone;
    
    public BillandReceipt(String mnumber, String date, String previous, String current, String unitconsumed, String totalpayable,
            String updname, String updadd, String updphone){
        super("Electricity Bill Receipt");
        
        initComponents();
        this.mnumber = mnumber;
        this.date = date;
        this.previous = previous;
        this.current = current;
        this.unitconsumed = unitconsumed;
        this.totalpayable = totalpayable;
        this.updname = updname;
        this.updadd = updadd;
        this.updphone = updphone;
        
        
        
        
    }
            
            
    public BillandReceipt() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        copy1 = new main.copy();
        place = new javax.swing.JLabel();
        copy2 = new main.copy();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        copy3 = new main.copy();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        actual_consump = new javax.swing.JTextField();
        billPeriod = new javax.swing.JTextField();
        billdate = new javax.swing.JTextField();
        dateMeterRead = new javax.swing.JTextField();
        dateNextRead = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        meter_number = new javax.swing.JTextField();
        curr_read = new javax.swing.JTextField();
        prev_read = new javax.swing.JTextField();
        copy4 = new main.copy();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        metNumber = new javax.swing.JTextField();
        due = new javax.swing.JTextField();
        payable = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eleclogo.png"))); // NOI18N
        logo.setText("jLabel6");
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoMousePressed(evt);
            }
        });
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 120, 80));

        fname.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        fname.setForeground(new java.awt.Color(51, 51, 51));
        fname.setText("Russell Kelvin Anthony Loreto");
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 31, 291, 19));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Actual Consumption");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 140, 20));

        copy1.setBackground(new java.awt.Color(11, 6, 42));

        javax.swing.GroupLayout copy1Layout = new javax.swing.GroupLayout(copy1);
        copy1.setLayout(copy1Layout);
        copy1Layout.setHorizontalGroup(
            copy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        copy1Layout.setVerticalGroup(
            copy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(copy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 93, 450, 3));

        place.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        place.setForeground(new java.awt.Color(102, 102, 102));
        place.setText("Bagong Silang, Caloocan City");
        jPanel1.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 56, 345, -1));

        copy2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout copy2Layout = new javax.swing.GroupLayout(copy2);
        copy2.setLayout(copy2Layout);
        copy2Layout.setHorizontalGroup(
            copy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        copy2Layout.setVerticalGroup(
            copy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(copy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 130, 450, 3));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Your Electric Bill");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 110, 110, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Billing Period");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Bill Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Date of Meter Reading");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 140, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Date of Next Reading");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 140, 20));

        copy3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout copy3Layout = new javax.swing.GroupLayout(copy3);
        copy3.setLayout(copy3Layout);
        copy3Layout.setHorizontalGroup(
            copy3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        copy3Layout.setVerticalGroup(
            copy3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(copy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 205, 450, 3));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Rate this Month");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 140, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Meter Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 140, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Current Reading");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 140, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Previous Reading");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 140, 20));

        actual_consump.setEditable(false);
        actual_consump.setBackground(new java.awt.Color(255, 255, 255));
        actual_consump.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actual_consump.setForeground(new java.awt.Color(51, 51, 51));
        actual_consump.setText("200 kWh");
        actual_consump.setBorder(null);
        jPanel1.add(actual_consump, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 150, 23));

        billPeriod.setEditable(false);
        billPeriod.setBackground(new java.awt.Color(255, 255, 255));
        billPeriod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        billPeriod.setForeground(new java.awt.Color(51, 51, 51));
        billPeriod.setText("Jan 02 to Feb 01 2023");
        billPeriod.setBorder(null);
        billPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billPeriodActionPerformed(evt);
            }
        });
        jPanel1.add(billPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 160, 20));

        billdate.setEditable(false);
        billdate.setBackground(new java.awt.Color(255, 255, 255));
        billdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        billdate.setForeground(new java.awt.Color(51, 51, 51));
        billdate.setText("Feb 01 2023");
        billdate.setBorder(null);
        jPanel1.add(billdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 150, 20));

        dateMeterRead.setEditable(false);
        dateMeterRead.setBackground(new java.awt.Color(255, 255, 255));
        dateMeterRead.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateMeterRead.setForeground(new java.awt.Color(51, 51, 51));
        dateMeterRead.setText("Jan 02 2023");
        dateMeterRead.setBorder(null);
        jPanel1.add(dateMeterRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 150, 20));

        dateNextRead.setEditable(false);
        dateNextRead.setBackground(new java.awt.Color(255, 255, 255));
        dateNextRead.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateNextRead.setForeground(new java.awt.Color(51, 51, 51));
        dateNextRead.setText("Feb 01 2023");
        dateNextRead.setBorder(null);
        jPanel1.add(dateNextRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 150, 20));

        rate.setEditable(false);
        rate.setBackground(new java.awt.Color(255, 255, 255));
        rate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rate.setForeground(new java.awt.Color(51, 51, 51));
        rate.setText("₱11.3168 (April)");
        rate.setBorder(null);
        jPanel1.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 150, 23));

        meter_number.setEditable(false);
        meter_number.setBackground(new java.awt.Color(255, 255, 255));
        meter_number.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meter_number.setForeground(new java.awt.Color(51, 51, 51));
        meter_number.setText("1234567890");
        meter_number.setBorder(null);
        jPanel1.add(meter_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 150, 23));

        curr_read.setEditable(false);
        curr_read.setBackground(new java.awt.Color(255, 255, 255));
        curr_read.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curr_read.setForeground(new java.awt.Color(51, 51, 51));
        curr_read.setText("3000");
        curr_read.setBorder(null);
        jPanel1.add(curr_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, 23));

        prev_read.setEditable(false);
        prev_read.setBackground(new java.awt.Color(255, 255, 255));
        prev_read.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prev_read.setForeground(new java.awt.Color(51, 51, 51));
        prev_read.setText("2800");
        prev_read.setBorder(null);
        jPanel1.add(prev_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 150, 23));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Meter Number");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Due Date");

        metNumber.setEditable(false);
        metNumber.setBackground(new java.awt.Color(212, 238, 252));
        metNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        metNumber.setForeground(new java.awt.Color(51, 51, 51));
        metNumber.setText("1234567890");
        metNumber.setBorder(null);

        due.setEditable(false);
        due.setBackground(new java.awt.Color(212, 238, 252));
        due.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        due.setForeground(new java.awt.Color(51, 51, 51));
        due.setText("Feb 02 2023");
        due.setBorder(null);

        payable.setEditable(false);
        payable.setBackground(new java.awt.Color(212, 238, 252));
        payable.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        payable.setForeground(new java.awt.Color(51, 51, 51));
        payable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        payable.setText("₱2263.36");
        payable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout copy4Layout = new javax.swing.GroupLayout(copy4);
        copy4.setLayout(copy4Layout);
        copy4Layout.setHorizontalGroup(
            copy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copy4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(copy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(copy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(due, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(copy4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(payable, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        copy4Layout.setVerticalGroup(
            copy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copy4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(copy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(copy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payable, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(copy4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 280, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoMousePressed

    private void billPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billPeriodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillandReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillandReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillandReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillandReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillandReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField actual_consump;
    public static javax.swing.JTextField billPeriod;
    public static javax.swing.JTextField billdate;
    private main.copy copy1;
    private main.copy copy2;
    private main.copy copy3;
    private main.copy copy4;
    public static javax.swing.JTextField curr_read;
    public static javax.swing.JTextField dateMeterRead;
    public static javax.swing.JTextField dateNextRead;
    public static javax.swing.JTextField due;
    public static javax.swing.JLabel fname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    public static javax.swing.JTextField metNumber;
    public static javax.swing.JTextField meter_number;
    public static javax.swing.JTextField payable;
    public static javax.swing.JLabel place;
    public static javax.swing.JTextField prev_read;
    public static javax.swing.JTextField rate;
    // End of variables declaration//GEN-END:variables
}
